// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 001_bulbs.sql

package database

import (
	"context"
	"time"
)

const addBulb = `-- name: AddBulb :one
INSERT INTO bulbs (mac, created_at, updated_at, ip, name)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING mac, created_at, updated_at, ip, name
`

type AddBulbParams struct {
	Mac       string
	CreatedAt time.Time
	UpdatedAt time.Time
	Ip        string
	Name      string
}

func (q *Queries) AddBulb(ctx context.Context, arg AddBulbParams) (Bulb, error) {
	row := q.db.QueryRowContext(ctx, addBulb,
		arg.Mac,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Ip,
		arg.Name,
	)
	var i Bulb
	err := row.Scan(
		&i.Mac,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ip,
		&i.Name,
	)
	return i, err
}

const getAllBulbs = `-- name: GetAllBulbs :many
SELECT mac, created_at, updated_at, ip, name FROM bulbs
`

func (q *Queries) GetAllBulbs(ctx context.Context) ([]Bulb, error) {
	rows, err := q.db.QueryContext(ctx, getAllBulbs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bulb
	for rows.Next() {
		var i Bulb
		if err := rows.Scan(
			&i.Mac,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ip,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBulb = `-- name: UpdateBulb :exec

UPDATE bulbs
SET ip = ?, updated_at = ?
WHERE mac = ?
`

type UpdateBulbParams struct {
	Ip        string
	UpdatedAt time.Time
	Mac       string
}

func (q *Queries) UpdateBulb(ctx context.Context, arg UpdateBulbParams) error {
	_, err := q.db.ExecContext(ctx, updateBulb, arg.Ip, arg.UpdatedAt, arg.Mac)
	return err
}
