// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 001_bulbs.sql

package database

import (
	"context"
	"time"
)

const addBulb = `-- name: AddBulb :one
INSERT INTO bulbs (mac, created_at, updated_at, ip, name, is_reachable)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING mac, created_at, updated_at, ip, name, is_reachable
`

type AddBulbParams struct {
	Mac         string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Ip          string
	Name        string
	IsReachable bool
}

func (q *Queries) AddBulb(ctx context.Context, arg AddBulbParams) (Bulb, error) {
	row := q.db.QueryRowContext(ctx, addBulb,
		arg.Mac,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Ip,
		arg.Name,
		arg.IsReachable,
	)
	var i Bulb
	err := row.Scan(
		&i.Mac,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ip,
		&i.Name,
		&i.IsReachable,
	)
	return i, err
}

const deleteBulb = `-- name: DeleteBulb :exec

DELETE FROM bulbs
where mac = ?
`

func (q *Queries) DeleteBulb(ctx context.Context, mac string) error {
	_, err := q.db.ExecContext(ctx, deleteBulb, mac)
	return err
}

const getAllBulbs = `-- name: GetAllBulbs :many
SELECT mac, created_at, updated_at, ip, name, is_reachable FROM bulbs
`

func (q *Queries) GetAllBulbs(ctx context.Context) ([]Bulb, error) {
	rows, err := q.db.QueryContext(ctx, getAllBulbs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bulb
	for rows.Next() {
		var i Bulb
		if err := rows.Scan(
			&i.Mac,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ip,
			&i.Name,
			&i.IsReachable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBulbIp = `-- name: UpdateBulbIp :exec

UPDATE bulbs
SET ip = ?, updated_at = ?
WHERE mac = ?
`

type UpdateBulbIpParams struct {
	Ip        string
	UpdatedAt time.Time
	Mac       string
}

func (q *Queries) UpdateBulbIp(ctx context.Context, arg UpdateBulbIpParams) error {
	_, err := q.db.ExecContext(ctx, updateBulbIp, arg.Ip, arg.UpdatedAt, arg.Mac)
	return err
}

const updateBulbName = `-- name: UpdateBulbName :exec

UPDATE bulbs
SET name = ?, updated_at = ?
WHERE mac = ?
`

type UpdateBulbNameParams struct {
	Name      string
	UpdatedAt time.Time
	Mac       string
}

func (q *Queries) UpdateBulbName(ctx context.Context, arg UpdateBulbNameParams) error {
	_, err := q.db.ExecContext(ctx, updateBulbName, arg.Name, arg.UpdatedAt, arg.Mac)
	return err
}
