// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_plex.sql

package database

import (
	"context"
	"database/sql"
)

const addPlexAccount = `-- name: AddPlexAccount :one

INSERT INTO accounts (id, title, thumb)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, title, thumb
`

type AddPlexAccountParams struct {
	ID    int64
	Title string
	Thumb sql.NullString
}

func (q *Queries) AddPlexAccount(ctx context.Context, arg AddPlexAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addPlexAccount, arg.ID, arg.Title, arg.Thumb)
	var i Account
	err := row.Scan(&i.ID, &i.Title, &i.Thumb)
	return i, err
}

const addPlexDevice = `-- name: AddPlexDevice :one

INSERT INTO devices (id, name, product)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, name, product
`

type AddPlexDeviceParams struct {
	ID      int64
	Name    string
	Product string
}

func (q *Queries) AddPlexDevice(ctx context.Context, arg AddPlexDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, addPlexDevice, arg.ID, arg.Name, arg.Product)
	var i Device
	err := row.Scan(&i.ID, &i.Name, &i.Product)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec

DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec

DELETE FROM devices
WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, title, thumb FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Title, &i.Thumb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDevices = `-- name: GetAllDevices :many

SELECT id, name, product FROM devices
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(&i.ID, &i.Name, &i.Product); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
