// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_plex.sql

package database

import (
	"context"
)

const addPlexAccount = `-- name: AddPlexAccount :one

INSERT INTO accounts (id, title)
VALUES (
    ?,
    ?
)
RETURNING id, title
`

type AddPlexAccountParams struct {
	ID    int64
	Title string
}

func (q *Queries) AddPlexAccount(ctx context.Context, arg AddPlexAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addPlexAccount, arg.ID, arg.Title)
	var i Account
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const addPlexPlayer = `-- name: AddPlexPlayer :one

INSERT INTO players (uuid, title, public_address)
VALUES (
    ?,
    ?,
    ?
)
RETURNING uuid, title, public_address
`

type AddPlexPlayerParams struct {
	Uuid          string
	Title         string
	PublicAddress string
}

func (q *Queries) AddPlexPlayer(ctx context.Context, arg AddPlexPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, addPlexPlayer, arg.Uuid, arg.Title, arg.PublicAddress)
	var i Player
	err := row.Scan(&i.Uuid, &i.Title, &i.PublicAddress)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec

DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deletePlayer = `-- name: DeletePlayer :exec

DELETE FROM players
WHERE uuid = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, uuid)
	return err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, title FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlayers = `-- name: GetAllPlayers :many

SELECT uuid, title, public_address FROM players
`

func (q *Queries) GetAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.Uuid, &i.Title, &i.PublicAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
