// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_plex.sql

package database

import (
	"context"
	"database/sql"
)

const addPlexAccount = `-- name: AddPlexAccount :one

INSERT INTO accounts (id, title, thumb)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, title, thumb
`

type AddPlexAccountParams struct {
	ID    int64
	Title string
	Thumb sql.NullString
}

func (q *Queries) AddPlexAccount(ctx context.Context, arg AddPlexAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addPlexAccount, arg.ID, arg.Title, arg.Thumb)
	var i Account
	err := row.Scan(&i.ID, &i.Title, &i.Thumb)
	return i, err
}

const addPlexPlayer = `-- name: AddPlexPlayer :one

INSERT INTO players (id, name, last_seen)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, name, last_seen
`

type AddPlexPlayerParams struct {
	ID       int64
	Name     string
	LastSeen string
}

func (q *Queries) AddPlexPlayer(ctx context.Context, arg AddPlexPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, addPlexPlayer, arg.ID, arg.Name, arg.LastSeen)
	var i Player
	err := row.Scan(&i.ID, &i.Name, &i.LastSeen)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec

DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deletePlayer = `-- name: DeletePlayer :exec

DELETE FROM players
WHERE id = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, title, thumb FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Title, &i.Thumb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlayers = `-- name: GetAllPlayers :many

SELECT id, name, last_seen FROM players
`

func (q *Queries) GetAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
