// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 003_rules.sql

package database

import (
	"context"
	"database/sql"
)

const addRule = `-- name: AddRule :one
INSERT INTO rules (id, condition, action)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, condition, "action", name
`

type AddRuleParams struct {
	ID        string
	Condition string
	Action    string
}

func (q *Queries) AddRule(ctx context.Context, arg AddRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, addRule, arg.ID, arg.Condition, arg.Action)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Condition,
		&i.Action,
		&i.Name,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec

DELETE FROM rules
WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getAllRules = `-- name: GetAllRules :many

SELECT id, condition, "action", name FROM rules
`

func (q *Queries) GetAllRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, getAllRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Condition,
			&i.Action,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleName = `-- name: UpdateRuleName :exec

UPDATE rules
SET name = ?
WHERE id = ?
`

type UpdateRuleNameParams struct {
	Name sql.NullString
	ID   string
}

func (q *Queries) UpdateRuleName(ctx context.Context, arg UpdateRuleNameParams) error {
	_, err := q.db.ExecContext(ctx, updateRuleName, arg.Name, arg.ID)
	return err
}
