// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID    int64
	Title string
	Thumb sql.NullString
}

type Bulb struct {
	Mac         string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Ip          string
	Name        string
	IsReachable bool
}

type Player struct {
	ID       int64
	Name     string
	LastSeen string
}

type Rule struct {
	ID        string
	Condition string
	Action    string
}
